[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# patch for changing interest out in state_events
[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
pattern = '''if G.GAME.dollars >= 5 and not G.GAME.modifiers.no_interest then
        add_round_eval_row({bonus = true, name='interest', pitch = pitch, dollars = G.GAME.interest_amount*math.min(math.floor(G.GAME.dollars/5), G.GAME.interest_cap/5)})'''
match_indent = true
position = 'at'
payload = '''if (G.GAME.dollars >= 5 or G.GAME.shareholder) and not G.GAME.modifiers.no_interest then
if G.GAME.shareholder then
    add_round_eval_row({bonus = true, name='shareholder_interest', pitch = pitch, dollars = G.GAME.interest_amount*math.floor(G.GAME.chips / G.GAME.blind.chips), div = G.GAME.blind.chips})
else
    add_round_eval_row({bonus = true, name='interest', pitch = pitch, dollars = G.GAME.interest_amount*math.min(math.floor(G.GAME.dollars/5), G.GAME.interest_cap/5)})
end'''

[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
pattern = '''dollars = dollars + G.GAME.interest_amount*math.min(math.floor(G.GAME.dollars/5), G.GAME.interest_cap/5)'''
match_indent = true
position = 'at'
payload = '''if G.GAME.shareholder then
    dollars = dollars + G.GAME.interest_amount*math.floor(G.GAME.chips / G.GAME.blind.chips)
else
    dollars = dollars + G.GAME.interest_amount*math.min(math.floor(G.GAME.dollars/5), G.GAME.interest_cap/5)
end'''

# patch for displaying text on round over screen
[[patches]]
[patches.pattern]
target = 'functions/common_events.lua'
pattern = '''table.insert(left_text,{n=G.UIT.O, config={object = DynaText({string = {" "..localize{type = 'variable', key = 'interest', vars = {G.GAME.interest_amount, 5, G.GAME.interest_amount*G.GAME.interest_cap/5}}}, colours = {G.C.UI.TEXT_LIGHT}, shadow = true, pop_in = 0, scale = 0.4*scale, silent = true})}})'''
match_indent = true
position = 'after'
payload = '''elseif config.name == 'shareholder_interest' then
    local div = G.GAME.blind.chips
    table.insert(left_text, {n=G.UIT.T, config={text = num_dollars, scale = 0.8*scale, colour = G.C.MONEY, shadow = true, juice = true}})
    table.insert(left_text,{n=G.UIT.O, config={object = DynaText({string = {" "..localize{type = 'variable', key = 'shareholder_interest', vars = {(G.GAME.chips / config.div), math.floor(G.GAME.chips / config.div)}}}, colours = {G.C.UI.TEXT_LIGHT}, shadow = true, pop_in = 0, scale = 0.4*scale, silent = true})}})
'''


