[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# this patches Hiker to display the 'buffed' sticker, granted to any playing
# card that has unseen perma bonuses
[[patches]]
[patches.pattern]
target = 'card.lua'
pattern = '''context.other_card.ability.perma_bonus = context.other_card.ability.perma_bonus + self.ability.extra'''
match_indent = true
position = 'after'
payload = '''-- vf_patch buffed
context.other_card.ability['vfusion_buffed'] = 'vfusion_buffed'
context.other_card.ability['vfusion_b_chips'] = 'vfusion_b_chips'
-- / vf_patch buffed patch'''

# this patches copy_card to correctly copy sticker
[[patches]]
[patches.pattern]
target = 'functions/common_events.lua'
pattern = '''if other.params then
        new_card.params = other.params
        new_card.params.playing_card = playing_card
    end'''
match_indent = true
position = 'after'
payload = '''-- vf_patch buffed
new_card.ability['vfusion_buffed'] = other.ability['vfusion_buffed'] or nil
new_card.ability['vfusion_b_chips'] = other.ability['vfusion_b_chips'] or nil
new_card.ability['vfusion_b_mult'] = other.ability['vfusion_b_mult'] or nil
new_card.ability['vfusion_b_x_mult'] = other.ability['vfusion_b_x_mult'] or nil
new_card.ability['vfusion_b_h_x_mult'] = other.ability['vfusion_b_h_x_mult'] or nil
new_card.ability['vfusion_b_dollars'] = other.ability['vfusion_b_dollars'] or nil
-- / vf_patch buffed patch'''

