[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# this patches Hiker to display the 'buffed' sticker, granted to any playing
# card that has unseen perma bonuses
[[patches]]
[patches.pattern]
target = 'card.lua'
pattern = '''context.other_card.ability.perma_bonus = context.other_card.ability.perma_bonus + self.ability.extra'''
match_indent = true
position = 'after'
payload = '''-- vf_patch buffed
context.other_card.ability['vfusion_buffed'] = 'vfusion_buffed'
-- / vf_patch buffed patch'''

# this patches Death to correctly copy sticker
[[patches]]
[patches.pattern]
target = 'card.lua'
pattern = '''if G.hand.highlighted[i] ~= rightmost then
                        copy_card(rightmost, G.hand.highlighted[i])
                    end'''
match_indent = true
position = 'after'
payload = '''-- vf_patch buffed
G.hand.highlighted[i].ability['vfusion_buffed'] = rightmost.ability['vfusion_buffed'] or nil
-- / vf_patch buffed patch'''

