[manifest]
version = "1.0.0"
dump_lua = true
priority = 1

[[patches]]
[patches.pattern]
target = 'functions/common_events.lua'
pattern = '''function ease_dollars(mod, instant)'''
match_indent = true
position = 'at'
payload = '''-- vf_patch dead_letters
function ease_dollars(mod, instant, from_joker)
-- / vf_patch dead_letters'''

[[patches]]
[patches.pattern]
target = 'functions/common_events.lua'
pattern = '''local dollar_UI = G.HUD:get_UIE_by_ID('dollar_text_UI')'''
match_indent = true
position = 'before'
payload = '''-- vf_patch dead_letters
if from_joker then table.insert(G.GAME.dead_letters_buffer, mod) end
-- / vf_patch dead_letters'''

[[patches]]
[patches.pattern]
target = 'card.lua'
pattern = '''ease_dollars(self.ability.extra)'''
match_indent = true
position = 'at'
payload = '''-- vf_patch dead_letters
ease_dollars(self.ability.extra, nil, true)
-- / vf_patch dead_letters'''

# Delayed gratification
[[patches]]
[patches.pattern]
target = 'card.lua'
pattern = '''if self.ability.name == 'Delayed Gratification' and G.GAME.current_round.discards_used == 0 and G.GAME.current_round.discards_left > 0 then'''
match_indent = true
position = 'after'
payload = '''-- vf_patch dead_letters
table.insert(G.GAME.dead_letters_buffer, G.GAME.current_round.discards_left*self.ability.extra)
-- / vf_patch dead_letters'''

# Satellite
[[patches]]
[patches.pattern]
target = 'card.lua'
pattern = '''if planets_used == 0 then return end'''
match_indent = true
position = 'after'
payload = '''-- vf_patch dead_letters
table.insert(G.GAME.dead_letters_buffer, self.ability.extra*planets_used)
-- / vf_patch dead_letters'''

# Rocket
[[patches]]
[patches.pattern]
target = 'card.lua'
pattern = '''return self.ability.extra.dollars'''
match_indent = true
position = 'before'
payload = '''-- vf_patch dead_letters
table.insert(G.GAME.dead_letters_buffer, self.ability.extra.dollars)
-- / vf_patch dead_letters'''

# Cloud 9
[[patches]]
[patches.pattern]
target = 'card.lua'
pattern = '''return self.ability.extra*(self.ability.nine_tally)'''
match_indent = true
position = 'before'
payload = '''-- vf_patch dead_letters
table.insert(G.GAME.dead_letters_buffer, self.ability.extra*(self.ability.nine_tally))
-- / vf_patch dead_letters'''

# Golden Joker
[[patches]]
[patches.pattern]
target = 'card.lua'
pattern = '''if self.ability.set == "Joker" then
        if self.ability.name == 'Golden Joker' then'''
match_indent = true
position = 'after'
payload = '''-- vf_patch dead_letters
table.insert(G.GAME.dead_letters_buffer, self.ability.extra)
-- / vf_patch dead_letters'''

# Business Card
[[patches]]
[patches.pattern]
target = 'card.lua'
pattern = '''pseudorandom('business') < G.GAME.probabilities.normal/self.ability.extra then'''
match_indent = true
position = 'after'
payload = '''-- vf_patch dead_letters
table.insert(G.GAME.dead_letters_buffer, 2)
-- / vf_patch dead_letters'''

# Golden Ticket
[[patches]]
[patches.pattern]
target = 'card.lua'
pattern = '''if self.ability.name == 'Golden Ticket' and
                    SMODS.has_enhancement(context.other_card, 'm_gold') then'''
match_indent = true
position = 'after'
payload = '''-- vf_patch dead_letters
    table.insert(G.GAME.dead_letters_buffer, self.ability.extra)
    -- / vf_patch dead_letters'''

# Faceless Joker
[[patches]]
[patches.pattern]
target = 'card.lua'
pattern = '''func = function()
                            ease_dollars(self.ability.extra.dollars)'''
match_indent = true
position = 'at'
payload = '''-- vf_patch dead_letters
func = function()
    ease_dollars(self.ability.extra.dollars, nil, true)
-- / vf_patch dead_letters'''
    
# To-Do List
[[patches]]
[patches.pattern]
target = 'card.lua'
pattern = '''if self.ability.name == 'To Do List' and context.scoring_name == self.ability.to_do_poker_hand then
                        ease_dollars(self.ability.extra.dollars)'''
match_indent = true
position = 'at'
payload = '''-- vf_patch dead_letters
if self.ability.name == 'To Do List' and context.scoring_name == self.ability.to_do_poker_hand then
    ease_dollars(self.ability.extra.dollars, nil, true)
-- / vf_patch dead_letters'''

# Reserved Parking
[[patches]]
[patches.pattern]
target = 'card.lua'
pattern = '''G.GAME.dollar_buffer = (G.GAME.dollar_buffer or 0) + self.ability.extra.dollars'''
match_indent = true
position = 'before'
payload = '''-- vf_patch dead_letters
table.insert(G.GAME.dead_letters_buffer, self.ability.extra.dollars)
-- / vf_patch dead_letters'''

# Rough gem
[[patches]]
[patches.pattern]
target = 'card.lua'
pattern = '''context.other_card:is_suit("Diamonds") then'''
match_indent = true
position = 'after'
payload = '''-- vf_patch dead_letters
    table.insert(G.GAME.dead_letters_buffer, self.ability.extra)
-- / vf_patch dead_letters'''