[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = 'card.lua'
pattern = '''if obj.use and type(obj.use) == 'function' then'''
match_indent = true
position = 'before'
payload = '''-- vf etteilla patch
if G.GAME.etteilla and not self.etteilla and self.ability.set == 'Tarot' then
  local etts = SMODS.find_card('j_vfusion_etteilla')
  for i = 1, #etts or 1 do
    if #G.consumeables.cards + G.GAME.consumeable_buffer < G.consumeables.config.card_limit then
      G.GAME.consumeable_buffer = G.GAME.consumeable_buffer + 1
      G.E_MANAGER:add_event(Event({
        func = function()
          G.GAME.consumeable_buffer = 0
          local t = SMODS.add_card({
            set = 'Tarot', 
            area = G.consumables,
            key = self.config.center_key,
            skip_materialize = false,
            key_append = 'etteilla', 
            no_edition = true
          })
          t.etteilla = true
        return true
        end
      }))
    end
  end
end
-- /vf etteilla patch'''


