[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = 'tag.lua'
pattern = '''if _context.type == 'eval' then '''
match_indent = true
position = 'before'
payload = '''G.GAME.used_tag_count = G.GAME.used_tag_count + 1'''
