[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = 'tag.lua'
pattern = '''function Tag:yep(message, _colour, func)'''
match_indent = true
position = 'after'
payload = '''G.GAME.used_tag_count = G.GAME.used_tag_count + 1'''
